-- 코드를 작성해주세요
SELECT
    t1.ID
FROM ECOLI_DATA t1
LEFT JOIN ECOLI_DATA t2
    ON t1.PARENT_ID = t2.ID
LEFT JOIN ECOLI_DATA t3
    ON t2.PARENT_ID = t3.ID
WHERE t3.PARENT_ID IS NULL AND t3.ID IS NOT NULL
ORDER BY t1.ID
