-- 코드를 입력하세요
SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT FROM ((SELECT ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE FROM ONLINE_SALE ONS
WHERE DATE_FORMAT(ONS.SALES_DATE, '%Y-%m') = '2022-03')
UNION ALL
(SELECT OFFLINE_SALE_ID, NULL , PRODUCT_ID, SALES_AMOUNT, DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE FROM OFFLINE_SALE OFFS
WHERE DATE_FORMAT(OFFS.SALES_DATE, '%Y-%m') = '2022-03')
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID) A;