-- 코드를 입력하세요
WITH RECURSIVE CTE (N)
AS (
    SELECT 0
    UNION ALL
    SELECT N+1
    FROM CTE
    WHERE N < 23
)

SELECT CTE.N, SUM(IF(CTE.N = HOUR(DATETIME), 1, 0)) COUNT
FROM CTE, ANIMAL_OUTS
GROUP BY CTE.N
ORDER BY CTE.N