-- 코드를 작성해주세요
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO AS INFO2
RIGHT JOIN 
            (SELECT NAME.FISH_TYPE, FISH_NAME,  
                          MAX(LENGTH) AS MAX_LENGTH
            FROM FISH_INFO AS INFO
            LEFT JOIN FISH_NAME_INFO AS NAME ON INFO.FISH_TYPE = NAME.FISH_TYPE
            GROUP BY 1, 2) AS TEMP ON (INFO2.FISH_TYPE, INFO2.LENGTH) = (TEMP.FISH_TYPE, TEMP.MAX_LENGTH)
ORDER BY ID ASC